# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         WWW-Scraper-ISBN
version:      0.25
version_from: ISBN.pm
installdirs:  site
requires:
    Carp:                          1
    WWW::Scraper::ISBN::Record:    0.15

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.20
