--- #YAML:1.0
name:                     WWW-Scraper-ISBN
version:                  0.28
abstract:                 Retrieve information about books from online sources
author:
  - Andy Schamp <andy@schamp.net>
  - Barbie <barbie@cpan.org>

license:                  artistic_2
distribution_type:        module
installdirs:              site

requires:
  perl:                           5.006
  Carp:                           1.00
  WWW::Scraper::ISBN::Driver:     0.20
  WWW::Scraper::ISBN::Record:     0.19
recommends:
  Test::CPAN::Meta:               0
  Test::CPAN::Meta::JSON:         0
  Test::Pod:                      1.00
  Test::Pod::Coverage:            0.08
build_requires:
  IO::File:                       0
  Test::More:                     0.88

provides:
  WWW::Scraper::ISBN:
    file:     lib/WWW/Scraper/ISBN.pm
    version:  0.28

no_index:
  directory:
    - t
    - examples

resources:
  license:    http://www.perlfoundation.org/artistic_license_2_0
  bugtracker: http://rt.cpan.org/Public/Dist/Display.html?Name=WWW-Scraper-ISBN
  repository: http://github.com/barbie/www-scraper-isbn

meta-spec:
   version:   1.4
   url:       http://module-build.sourceforge.net/META-spec-v1.4.html
generated_by: Hand 1.0
